---
- hosts: 
  - all

  # Variables Globales
  vars_files:
    - vars/main.yml
  roles:
    - 2p_2025_esposito

  tasks:
    
    
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"

